package com.bedrud.app.core.auth

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/** Bytes of the GCM nonce the cipher generates per write, stored in front of the ciphertext. */
private const val NONCE_BYTES = 12

/** Length of the GCM authentication tag, in bits. */
private const val TAG_BITS = 128

private const val KEYSTORE = "AndroidKeyStore"
private const val TRANSFORMATION = "AES/GCM/NoPadding"
private const val TAG = "KeystoreCipher"

/**
 * Seals values with an AES-GCM key held in the Android Keystore, where the key material cannot be
 * read out of the device.
 *
 * Each write gets its own nonce, generated by the platform rather than chosen here —
 * `setRandomizedEncryptionRequired` refuses a caller-supplied one, which is the protection worth
 * having, since a nonce reused across two writes under one key breaks GCM. The nonce is not
 * secret and is stored in front of the ciphertext.
 *
 * The key is created on first use and kept. It can still stop working: a backup restored onto
 * another device never carries it, and a lock-screen change can invalidate it. Both surface as a
 * failure to open a value, which is reported as null rather than thrown — see [decrypt].
 */
class KeystoreCipher(private val alias: String) : SecureCipher {

    // Opened on first use, not on construction: opening a credential file must never be the thing
    // that throws, or an unusable Keystore takes the app down before it can sign anyone out.
    private val keyStore by lazy { KeyStore.getInstance(KEYSTORE).apply { load(null) } }

    private fun generateKey(): SecretKey {
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private fun key(): SecretKey =
        (keyStore.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.secretKey ?: generateKey()

    override fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val sealed = cipher.doFinal(plaintext.toByteArray())
        return Base64.encodeToString(cipher.iv + sealed, Base64.NO_WRAP)
    }

    override fun decrypt(stored: String): String? {
        return try {
            val bytes = Base64.decode(stored, Base64.NO_WRAP)
            if (bytes.size <= NONCE_BYTES) return null
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                key(),
                GCMParameterSpec(TAG_BITS, bytes, 0, NONCE_BYTES),
            )
            String(cipher.doFinal(bytes, NONCE_BYTES, bytes.size - NONCE_BYTES))
        } catch (e: GeneralSecurityException) {
            // The key this value was sealed with is gone or no longer usable. Nothing here can
            // recover the value, and the caller reads it as absent.
            Log.w(TAG, "Stored value could not be opened", e)
            null
        } catch (e: IllegalArgumentException) {
            Log.w(TAG, "Stored value is not in the expected format", e)
            null
        }
    }
}
