version: 2

updates:
  # Gradle (Kotlin/Android dependencies)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: "deps"
    reviewers:
      - "narseh-ir"
    assignees:
      - "narseh-ir"
    groups:
      gradle-all:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: "deps(ci)"
    reviewers:
      - "narseh-ir"
    assignees:
      - "narseh-ir"
    groups:
      actions-all:
        patterns:
          - "*"
    open-pull-requests-limit: 5
