/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as MMeetIdRouteImport } from './routes/m.$meetId'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardSettingsVideoRouteImport } from './routes/dashboard/settings/video'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsAudioRouteImport } from './routes/dashboard/settings/audio'
import { Route as DashboardArchivedRoomIdRouteImport } from './routes/dashboard/archived_.$roomId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard/admin/settings'
import { Route as DashboardAdminRoomsRouteImport } from './routes/dashboard/admin/rooms'
import { Route as DashboardAdminRecordingsRouteImport } from './routes/dashboard/admin/recordings'
import { Route as DashboardAdminQueueRouteImport } from './routes/dashboard/admin/queue'
import { Route as DashboardAdminUsersRecentSignupsRouteImport } from './routes/dashboard/admin/users_.recent-signups'
import { Route as DashboardAdminUsersUserIdRouteImport } from './routes/dashboard/admin/users_.$userId'
import { Route as DashboardAdminRoomsEventsRouteImport } from './routes/dashboard/admin/rooms_.events'
import { Route as DashboardAdminRoomsRoomIdRouteImport } from './routes/dashboard/admin/rooms_.$roomId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const MMeetIdRoute = MMeetIdRouteImport.update({
  id: '/m/$meetId',
  path: '/m/$meetId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardSettingsVideoRoute = DashboardSettingsVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAudioRoute = DashboardSettingsAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardArchivedRoomIdRoute = DashboardArchivedRoomIdRouteImport.update({
  id: '/archived_/$roomId',
  path: '/archived/$roomId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminRoomsRoute = DashboardAdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminRecordingsRoute =
  DashboardAdminRecordingsRouteImport.update({
    id: '/recordings',
    path: '/recordings',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminQueueRoute = DashboardAdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminUsersRecentSignupsRoute =
  DashboardAdminUsersRecentSignupsRouteImport.update({
    id: '/users_/recent-signups',
    path: '/users/recent-signups',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminUsersUserIdRoute =
  DashboardAdminUsersUserIdRouteImport.update({
    id: '/users_/$userId',
    path: '/users/$userId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminRoomsEventsRoute =
  DashboardAdminRoomsEventsRouteImport.update({
    id: '/rooms_/events',
    path: '/rooms/events',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminRoomsRoomIdRoute =
  DashboardAdminRoomsRoomIdRouteImport.update({
    id: '/rooms_/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/m/$meetId': typeof MMeetIdRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/queue': typeof DashboardAdminQueueRoute
  '/dashboard/admin/recordings': typeof DashboardAdminRecordingsRoute
  '/dashboard/admin/rooms': typeof DashboardAdminRoomsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/archived/$roomId': typeof DashboardArchivedRoomIdRoute
  '/dashboard/settings/audio': typeof DashboardSettingsAudioRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/video': typeof DashboardSettingsVideoRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/rooms/$roomId': typeof DashboardAdminRoomsRoomIdRoute
  '/dashboard/admin/rooms/events': typeof DashboardAdminRoomsEventsRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
  '/dashboard/admin/users/recent-signups': typeof DashboardAdminUsersRecentSignupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/m/$meetId': typeof MMeetIdRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/queue': typeof DashboardAdminQueueRoute
  '/dashboard/admin/recordings': typeof DashboardAdminRecordingsRoute
  '/dashboard/admin/rooms': typeof DashboardAdminRoomsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/archived/$roomId': typeof DashboardArchivedRoomIdRoute
  '/dashboard/settings/audio': typeof DashboardSettingsAudioRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/video': typeof DashboardSettingsVideoRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/rooms/$roomId': typeof DashboardAdminRoomsRoomIdRoute
  '/dashboard/admin/rooms/events': typeof DashboardAdminRoomsEventsRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
  '/dashboard/admin/users/recent-signups': typeof DashboardAdminUsersRecentSignupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/m/$meetId': typeof MMeetIdRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/queue': typeof DashboardAdminQueueRoute
  '/dashboard/admin/recordings': typeof DashboardAdminRecordingsRoute
  '/dashboard/admin/rooms': typeof DashboardAdminRoomsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/archived_/$roomId': typeof DashboardArchivedRoomIdRoute
  '/dashboard/settings/audio': typeof DashboardSettingsAudioRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/video': typeof DashboardSettingsVideoRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/rooms_/$roomId': typeof DashboardAdminRoomsRoomIdRoute
  '/dashboard/admin/rooms_/events': typeof DashboardAdminRoomsEventsRoute
  '/dashboard/admin/users_/$userId': typeof DashboardAdminUsersUserIdRoute
  '/dashboard/admin/users_/recent-signups': typeof DashboardAdminUsersRecentSignupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/m/$meetId'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/admin/queue'
    | '/dashboard/admin/recordings'
    | '/dashboard/admin/rooms'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/archived/$roomId'
    | '/dashboard/settings/audio'
    | '/dashboard/settings/security'
    | '/dashboard/settings/video'
    | '/dashboard/admin/'
    | '/dashboard/settings/'
    | '/dashboard/admin/rooms/$roomId'
    | '/dashboard/admin/rooms/events'
    | '/dashboard/admin/users/$userId'
    | '/dashboard/admin/users/recent-signups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/m/$meetId'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin/queue'
    | '/dashboard/admin/recordings'
    | '/dashboard/admin/rooms'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/archived/$roomId'
    | '/dashboard/settings/audio'
    | '/dashboard/settings/security'
    | '/dashboard/settings/video'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/admin/rooms/$roomId'
    | '/dashboard/admin/rooms/events'
    | '/dashboard/admin/users/$userId'
    | '/dashboard/admin/users/recent-signups'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/m/$meetId'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/admin/queue'
    | '/dashboard/admin/recordings'
    | '/dashboard/admin/rooms'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/archived_/$roomId'
    | '/dashboard/settings/audio'
    | '/dashboard/settings/security'
    | '/dashboard/settings/video'
    | '/dashboard/admin/'
    | '/dashboard/settings/'
    | '/dashboard/admin/rooms_/$roomId'
    | '/dashboard/admin/rooms_/events'
    | '/dashboard/admin/users_/$userId'
    | '/dashboard/admin/users_/recent-signups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  MMeetIdRoute: typeof MMeetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/m/$meetId': {
      id: '/m/$meetId'
      path: '/m/$meetId'
      fullPath: '/m/$meetId'
      preLoaderRoute: typeof MMeetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/settings/video': {
      id: '/dashboard/settings/video'
      path: '/video'
      fullPath: '/dashboard/settings/video'
      preLoaderRoute: typeof DashboardSettingsVideoRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/audio': {
      id: '/dashboard/settings/audio'
      path: '/audio'
      fullPath: '/dashboard/settings/audio'
      preLoaderRoute: typeof DashboardSettingsAudioRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/archived_/$roomId': {
      id: '/dashboard/archived_/$roomId'
      path: '/archived/$roomId'
      fullPath: '/dashboard/archived/$roomId'
      preLoaderRoute: typeof DashboardArchivedRoomIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/rooms': {
      id: '/dashboard/admin/rooms'
      path: '/rooms'
      fullPath: '/dashboard/admin/rooms'
      preLoaderRoute: typeof DashboardAdminRoomsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/recordings': {
      id: '/dashboard/admin/recordings'
      path: '/recordings'
      fullPath: '/dashboard/admin/recordings'
      preLoaderRoute: typeof DashboardAdminRecordingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/queue': {
      id: '/dashboard/admin/queue'
      path: '/queue'
      fullPath: '/dashboard/admin/queue'
      preLoaderRoute: typeof DashboardAdminQueueRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/users_/recent-signups': {
      id: '/dashboard/admin/users_/recent-signups'
      path: '/users/recent-signups'
      fullPath: '/dashboard/admin/users/recent-signups'
      preLoaderRoute: typeof DashboardAdminUsersRecentSignupsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/users_/$userId': {
      id: '/dashboard/admin/users_/$userId'
      path: '/users/$userId'
      fullPath: '/dashboard/admin/users/$userId'
      preLoaderRoute: typeof DashboardAdminUsersUserIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/rooms_/events': {
      id: '/dashboard/admin/rooms_/events'
      path: '/rooms/events'
      fullPath: '/dashboard/admin/rooms/events'
      preLoaderRoute: typeof DashboardAdminRoomsEventsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/rooms_/$roomId': {
      id: '/dashboard/admin/rooms_/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/dashboard/admin/rooms/$roomId'
      preLoaderRoute: typeof DashboardAdminRoomsRoomIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminQueueRoute: typeof DashboardAdminQueueRoute
  DashboardAdminRecordingsRoute: typeof DashboardAdminRecordingsRoute
  DashboardAdminRoomsRoute: typeof DashboardAdminRoomsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminRoomsRoomIdRoute: typeof DashboardAdminRoomsRoomIdRoute
  DashboardAdminRoomsEventsRoute: typeof DashboardAdminRoomsEventsRoute
  DashboardAdminUsersUserIdRoute: typeof DashboardAdminUsersUserIdRoute
  DashboardAdminUsersRecentSignupsRoute: typeof DashboardAdminUsersRecentSignupsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminQueueRoute: DashboardAdminQueueRoute,
  DashboardAdminRecordingsRoute: DashboardAdminRecordingsRoute,
  DashboardAdminRoomsRoute: DashboardAdminRoomsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminRoomsRoomIdRoute: DashboardAdminRoomsRoomIdRoute,
  DashboardAdminRoomsEventsRoute: DashboardAdminRoomsEventsRoute,
  DashboardAdminUsersUserIdRoute: DashboardAdminUsersUserIdRoute,
  DashboardAdminUsersRecentSignupsRoute: DashboardAdminUsersRecentSignupsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardSettingsRouteChildren {
  DashboardSettingsAudioRoute: typeof DashboardSettingsAudioRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsVideoRoute: typeof DashboardSettingsVideoRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAudioRoute: DashboardSettingsAudioRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsVideoRoute: DashboardSettingsVideoRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardArchivedRoomIdRoute: typeof DashboardArchivedRoomIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardArchivedRoomIdRoute: DashboardArchivedRoomIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  MMeetIdRoute: MMeetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
