root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server/main.go"
  bin = "./tmp/server"
  full_bin = "CONFIG_PATH=./config.yaml ./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "dist", "frontend", "docs", "migrations"]
  exclude_file = []
  exclude_regex = ["_test\\.go$"]
  exclude_unchanged = true
  follow_symlink = false
  log = "build-errors.log"
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = false
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
