package remote

import (
	"fmt"
	"strings"
)

func livekitYAML(cfg *Config, nodeIP, apiSecret string) string {
	// node_ip is a fallback when STUN discovery fails; use_external_ip is preferred for remote peers.
	nodeIPLine := ""
	ipsIncludeBlock := ""
	if nodeIP != "" {
		nodeIPLine = fmt.Sprintf("  node_ip: %s\n", nodeIP)
		ipsIncludeBlock = fmt.Sprintf(`  ips:
    includes:
      - %s/32
`, nodeIP)
	}
	turnTLS := ""
	if cfg.acmeEnabled() {
		state := cfg.Provision.StateDir
		turnTLS = fmt.Sprintf(`  tls_port: 5349
  cert_file: %s/turn.crt
  key_file: %s/turn.key
  relay_range_start: 30000
  relay_range_end: 40000
`, state, state)
	}
	return fmt.Sprintf(`port: %d
rtc:
  tcp_port: %d
  port_range_start: %d
  port_range_end: %d
  use_external_ip: true
  use_ice_lite: false
  allow_tcp_fallback: true
  interfaces:
    excludes:
      - wg0
%s%slogging:
  level: info
turn:
  enabled: true
  domain: %s
%skeys:
  %s: %q
room:
  auto_create: true
  empty_timeout: 60
  departure_timeout: 60
  max_participants: 20
`,
		cfg.Traefik.LiveKitPort,
		cfg.Provision.LiveKitRTCPort,
		cfg.Provision.LiveKitRTCStart,
		cfg.Provision.LiveKitRTCEnd,
		nodeIPLine,
		ipsIncludeBlock,
		cfg.URLs.PublicHost,
		turnTLS,
		cfg.LiveKit.APIKey,
		apiSecret,
	)
}

func traefikStaticYAML(cfg *Config) string {
	if cfg.acmeEnabled() {
		email := cfg.Provision.ACMEmail
		if email == "" {
			email = "admin@" + cfg.URLs.PublicHost
		}
		acme := fmt.Sprintf(`
certificatesResolvers:
  letsencrypt:
    acme:
      email: %q
      storage: %q
      httpChallenge:
        entryPoint: web
`, email, cfg.Provision.StateDir+"/acme.json")
		return fmt.Sprintf(`# Generated by devcli remote provision
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
%s
providers:
  file:
    directory: %q
    watch: true

api:
  dashboard: false
  insecure: false
# HTTP routers are synced by: devcli remote traefik sync
`,
			acme,
			cfg.Traefik.DynamicDir,
		)
	}

	return fmt.Sprintf(`# Generated by devcli remote provision (HTTP only — enableACME: false)
entryPoints:
  web:
    address: ":80"
providers:
  file:
    directory: %q
    watch: true

api:
  dashboard: false
  insecure: false
# HTTP routers are synced by: devcli remote traefik sync
`,
		cfg.Traefik.DynamicDir,
	)
}

func livekitUnit(cfg *Config) string {
	return fmt.Sprintf(`[Unit]
Description=LiveKit Server (Bedrud remote debug)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/livekit-server --config %s/livekit.yaml
# always: LiveKit exits 0 when TURN cert files are missing (ACME not ready yet)
Restart=always
RestartSec=3
TimeoutStopSec=15
KillMode=mixed

[Install]
WantedBy=multi-user.target
`, cfg.Provision.StateDir)
}

func traefikUnit(cfg *Config) string {
	return fmt.Sprintf(`[Unit]
Description=Traefik (Bedrud remote debug)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/traefik --configFile=%s/traefik.yml
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
`, cfg.Provision.StateDir)
}

func wireguardServerConf(cfg *Config, serverPriv, clientPub, wanIface string) string {
	serverIP := strings.TrimSpace(cfg.WireGuard.RemoteTunnelIP)
	if serverIP == "" {
		serverIP = "10.0.0.1"
	}
	clientIP := strings.TrimSpace(cfg.WireGuard.LocalTunnelIP)
	if clientIP == "" {
		clientIP = "10.0.0.2"
	}
	return fmt.Sprintf(`[Interface]
Address = %s/24
ListenPort = %d
PrivateKey = %s
PostUp = iptables -A FORWARD -i %%i -j ACCEPT; iptables -t nat -A POSTROUTING -o %s -j MASQUERADE
PostDown = iptables -D FORWARD -i %%i -j ACCEPT; iptables -t nat -D POSTROUTING -o %s -j MASQUERADE

[Peer]
PublicKey = %s
AllowedIPs = %s/32
`,
		serverIP,
		cfg.Provision.WireGuardPort,
		serverPriv,
		wanIface,
		wanIface,
		clientPub,
		clientIP,
	)
}

func wireguardClientConf(cfg *Config, clientPriv, serverPub string) (string, error) {
	remoteIP := strings.TrimSpace(cfg.WireGuard.RemoteTunnelIP)
	if remoteIP == "" {
		remoteIP = "10.0.0.1"
	}
	endpoint, err := cfg.wireGuardEndpointResolved()
	if err != nil {
		return "", fmt.Errorf("wireguard endpoint: %w", err)
	}
	return fmt.Sprintf(`# Split-tunnel: only the debug server tunnel IP (api/livekit over WG, not whole server).
[Interface]
Address = %s/32
PrivateKey = %s

[Peer]
PublicKey = %s
Endpoint = %s
AllowedIPs = %s/32
PersistentKeepalive = 25
`,
		cfg.WireGuard.LocalTunnelIP,
		clientPriv,
		serverPub,
		endpoint,
		remoteIP,
	), nil
}