name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint workflow files
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run actionlint
        uses: reviewdog/action-actionlint@1758727be30241166609dad4c97588b6ad411f32 # v1
        with:
          fail_level: error
